version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  nginx:
    image: nginx
    expose:
      - '8080'
    deploy:
      replicas: 4
    environment:
      - VIRTUAL_HOST=coucou
